import { Figtree } from "next/font/google";

import Sidebar from "@/components/sidebar/sidebar";

import "./globals.css";
import Topbar from "@/components/topbar/topbar";
import Bottombar from "@/components/bottombar/bottombar";

const font = Figtree({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Topbar />
        <Sidebar>{children}</Sidebar>
        <Bottombar />
      </body>
    </html>
  );
}
