import { Figtree } from "next/font/google";

import { ThemeProvider } from "../components/theme-provider";
import Sidebar from "@/components_old/sidebar/sidebar";

import "./globals.css";
import Topbar from "@/components_old/topbar/topbar";
import Bottombar from "@/components_old/bottombar/bottombar";

const font = Figtree({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
